services:
  server: 
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - database:/var/lib/mongodb/data

volumes:
  database: